### ISSUE TITLE
name 'alsaaudio' not defined

### ISSUE THREAD

**Issue by DrTexx** [DrTexxOfficial/volux#26]
```
python3 -m volux
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/nick/Downloads/volux-develop/volux/__main__.py", line 37, in <module>
    mixer = cpaudio.MixerController()
  File "/Users/nick/Downloads/volux-develop/cpaudio/Platforms/Darwin/__init__.py", line 7, in __init__
    print("mixers:",alsaaudio.mixers())
NameError: name 'alsaaudio' is not defined
```

**Comment by DrTexx** [comment]
addressed in 56918fa607b0ccd72861438784496f052454522a
