### ISSUE TITLE
path to preferences needs tweaking

### ISSUE THREAD

**Issue by DrTexx** [DrTexxOfficial/volux#27]
```
python3 -m volux
uxTraceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/nick/Downloads/volux-develop/volux/__main__.py", line 43, in <module>
    with open("preferences.json") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'preferences.json'
```

**Comment by DrTexx** [comment]
Preferences deprecated, no longer applicable.
